name: Arch Updater

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Get Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install libraries
      run: npm install rss-parser parse-torrent
    - name: Run the version updater
      run: node updaters/arch.js
    - name: Configure Git
      run: git config --global user.name "Leo Herzog" && git config --global user.email "xd1936@gmail.com"
    - name: Add, Commit, and Push
      run: git add distros.json && git commit -m "Update Arch" && git push || echo "No changes"