name: IPFS Hashes Updater

on:
  schedule:
    - cron: '30 */4 * * *'

jobs:

  update-hashes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Get Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install libraries
      run: npm install ipfs
    - name: Configure Git
      run: git config --global user.name "Leo Herzog" && git config --global user.email "xd1936@gmail.com"
    - name: Add missing hashes
      run: node .github/ipfs-hashes-updater.js
    - name: Add, Commit, and Push
      run: git add distros.json && git commit -m "Add Missing IPFS Hashes" && git push || echo "No changes"