name: Prime IPFS Gateways

on:
  schedule:
    - cron: '0 0 * * *'

jobs:

  update-hashes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Get Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install libraries
      run: npm install node-fetch
    - name: Send Request
      run: node .github/prime-ipfs-gateways.js